### ISSUE TITLE
Add a drop down to filter user

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/plotapp#1]
Allow users to filter data based on an individual user vs all data.

**Comment by jeroenooms** [comment]
We can use the plotapp filter field for this, or the dashboard.

**Comment by rgmobilize** [comment]
Thanks. Where are these requests coming from?

On Oct 26, 2015, at 9:56 AM, Jeroen Ooms <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1<https://github.com/mobilizingcs/plotapp/issues/1>.

—
Reply to this email directly or view it on GitHub<https://github.com/mobilizingcs/plotapp/issues/1#event-445785301>.

Rob Gould
Vice-chair, Undergraduate Studies
Dept. of Statistics, UCLA
DataFest founder
rgould@stat.ucla.edu<mailto:rgould@stat.ucla.edu>
