### ISSUE TITLE
allow users to add lines to the plot

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/plotapp#22]
Request from @rgmobilize
Several teachers have mentioned that a cool feature would be to input a slope and intercept and have it plot a line while, at the same time, displaying the least-squares line.  For example, they would like students to guess the best fit line, have it plotted, and then compare to the actual  LS fit.

I suppose the main problem is the user interface?

**Comment by jeroenooms** [comment]
We have this now.
