### ISSUE TITLE
Drop unused factor levels from plots

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/plotapp#26]
This is on lausd with campaign "Binge Watching Demo".. Choose x-axis as genre.. 
Note: 
[Uploading plotapp_binge.pdf…]()
I can't seem to attach a screenshot.. Will send it to email.. 

Also in the data summary area, please add space after colon to make the data easier to read.. (requested by Rob).

**Comment by jeroenooms** [comment]
By default ggplot2 only plots categories that actually appear in the data. I pushed a fix https://github.com/mobilizingcs/plotapp/commit/9b6603e29f790b1dbda8c7f26760b784142c2b2e that now also displays the empty categories. Not sure if this is an improvement or not.
