### ISSUE TITLE
simplify some terminology in the x-axis drop-down list

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/plotapp#6]
- day -> day of the week
  - time -> time of day

**Comment by jeroenooms** [comment]
We deliberately show the actual variable names so that the user knows what to use if they want to enter something in the **filter** field, for example `day == "monday"`.

**Comment by jeroenooms** [comment]
Added some more informative select labels: https://github.com/mobilizingcs/plotapp/commit/c257abb45bf9afc88841ac23ddd4d7daee729ff9
